//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.18052
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace CacheIt {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class strings {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal strings() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("CacheIt.strings", typeof(strings).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Read is disabled because the object is disposing..
        /// </summary>
        internal static string CacheIt_IO_ReadDisabledDisposing {
            get {
                return ResourceManager.GetString("CacheIt_IO_ReadDisabledDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seek is disabled because the object is disposing..
        /// </summary>
        internal static string CacheIt_IO_SeekDisabledDisposing {
            get {
                return ResourceManager.GetString("CacheIt_IO_SeekDisabledDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Write is disabled because the object is disposing..
        /// </summary>
        internal static string CacheIt_IO_WriteDisabledDisposing {
            get {
                return ResourceManager.GetString("CacheIt_IO_WriteDisabledDisposing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Region Name is not supported by this implementation. .
        /// </summary>
        internal static string CacheIt_RegionName_not_supported {
            get {
                return ResourceManager.GetString("CacheIt_RegionName_not_supported", resourceCulture);
            }
        }
    }
}
