using System;
using System.Collections.Generic;
using System.Linq;
using System.Text;
namespace CacheIt.Tests.Unit
{
    public class Country
    {
        public string Code{get;set;}
        public string Name {get;set;}

        public static readonly Country[] Countries = new Country[] {
        new Country{ Code = "AF", Name= "Afghanistan"},
        new Country{ Code = "AL", Name= "Albania"},
        new Country{ Code = "DZ", Name= "Algeria"},
        new Country{ Code = "AS", Name= "American Samoa"},
        new Country{ Code = "AD", Name= "Andorra"},
        new Country{ Code = "AO", Name= "Angola"},
        new Country{ Code = "AI", Name= "Anguilla"},
        new Country{ Code = "AQ", Name= "Antarctica"},
        new Country{ Code = "AG", Name= "Antigua and Barbuda"},
        new Country{ Code = "AR", Name= "Argentina"},
        new Country{ Code = "AM", Name= "Armenia"},
        new Country{ Code = "AW", Name= "Aruba"},
        new Country{ Code = "AU", Name= "Australia"},
        new Country{ Code = "AT", Name= "Austria"},
        new Country{ Code = "AZ", Name= "Azerbaijan"},
        new Country{ Code = "BS", Name= "Bahamas"},
        new Country{ Code = "BH", Name= "Bahrain"},
        new Country{ Code = "BD", Name= "Bangladesh"},
        new Country{ Code = "BB", Name= "Barbados"},
        new Country{ Code = "BY", Name= "Belarus"},
        new Country{ Code = "BE", Name= "Belgium"},
        new Country{ Code = "BZ", Name= "Belize"},
        new Country{ Code = "BJ", Name= "Benin"},
        new Country{ Code = "BM", Name= "Bermuda"},
        new Country{ Code = "BT", Name= "Bhutan"},
        new Country{ Code = "BO", Name= "Bolivia"},
        new Country{ Code = "BA", Name= "Bosnia and Herzegovina"},
        new Country{ Code = "BW", Name= "Botswana"},
        new Country{ Code = "BV", Name= "Bouvet Island"},
        new Country{ Code = "BR", Name= "Brazil"},
        new Country{ Code = "IO", Name= "British Indian Ocean Territory"},
        new Country{ Code = "BN", Name= "Brunei Darussalam"},
        new Country{ Code = "BG", Name= "Bulgaria"},
        new Country{ Code = "BF", Name= "Burkina Faso"},
        new Country{ Code = "BI", Name= "Burundi"},
        new Country{ Code = "KH", Name= "Cambodia"},
        new Country{ Code = "CM", Name= "Cameroon"},
        new Country{ Code = "CA", Name= "Canada"},
        new Country{ Code = "CV", Name= "Cape Verde"},
        new Country{ Code = "KY", Name= "Cayman Islands"},
        new Country{ Code = "CF", Name= "Central African Republic"},
        new Country{ Code = "TD", Name= "Chad"},
        new Country{ Code = "CL", Name= "Chile"},
        new Country{ Code = "CN", Name= "China"},
        new Country{ Code = "CX", Name= "Christmas Island"},
        new Country{ Code = "CC", Name= "Cocos (Keeling Islands)"},
        new Country{ Code = "CO", Name= "Colombia"},
        new Country{ Code = "KM", Name= "Comoros"},
        new Country{ Code = "CG", Name= "Congo"},
        new Country{ Code = "CK", Name= "Cook Islands"},
        new Country{ Code = "CR", Name= "Costa Rica"},
        new Country{ Code = "CI", Name= "Cote D'Ivoire (Ivory Coast)"},
        new Country{ Code = "HR", Name= "Croatia (Hrvatska"},
        new Country{ Code = "CU", Name= "Cuba"},
        new Country{ Code = "CY", Name= "Cyprus"},
        new Country{ Code = "CZ", Name= "Czech Republic"},
        new Country{ Code = "DK", Name= "Denmark"},
        new Country{ Code = "DJ", Name= "Djibouti"},
        new Country{ Code = "DM", Name= "Dominica"},
        new Country{ Code = "DO", Name= "Dominican Republic"},
        new Country{ Code = "TP", Name= "East Timor"},
        new Country{ Code = "EC", Name= "Ecuador"},
        new Country{ Code = "EG", Name= "Egypt"},
        new Country{ Code = "SV", Name= "El Salvador"},
        new Country{ Code = "GQ", Name= "Equatorial Guinea"},
        new Country{ Code = "ER", Name= "Eritrea"},
        new Country{ Code = "EE", Name= "Estonia"},
        new Country{ Code = "ET", Name= "Ethiopia"},
        new Country{ Code = "FK", Name= "Falkland Islands (Malvinas)"},
        new Country{ Code = "FO", Name= "Faroe Islands"},
        new Country{ Code = "FJ", Name= "Fiji"},
        new Country{ Code = "FI", Name= "Finland"},
        new Country{ Code = "FR", Name= "France"},
        new Country{ Code = "FX", Name= "France, Metropolitan"},
        new Country{ Code = "GF", Name= "French Guiana"},
        new Country{ Code = "PF", Name= "French Polynesia"},
        new Country{ Code = "TF", Name= "French Southern Territories"},
        new Country{ Code = "GA", Name= "Gabon"},
        new Country{ Code = "GM", Name= "Gambia"},
        new Country{ Code = "GE", Name= "Georgia"},
        new Country{ Code = "DE", Name= "Germany"},
        new Country{ Code = "GH", Name= "Ghana"},
        new Country{ Code = "GI", Name= "Gibraltar"},
        new Country{ Code = "GR", Name= "Greece"},
        new Country{ Code = "GL", Name= "Greenland"},
        new Country{ Code = "GD", Name= "Grenada"},
        new Country{ Code = "GP", Name= "Guadeloupe"},
        new Country{ Code = "GU", Name= "Guam"},
        new Country{ Code = "GT", Name= "Guatemala"},
        new Country{ Code = "GN", Name= "Guinea"},
        new Country{ Code = "GW", Name= "Guinea-Bissau"},
        new Country{ Code = "GY", Name= "Guyana"},
        new Country{ Code = "HT", Name= "Haiti"},
        new Country{ Code = "HM", Name= "Heard and McDonald Islands"},
        new Country{ Code = "HN", Name= "Honduras"},
        new Country{ Code = "HK", Name= "Hong Kong"},
        new Country{ Code = "HU", Name= "Hungary"},
        new Country{ Code = "IS", Name= "Iceland"},
        new Country{ Code = "IN", Name= "India"},
        new Country{ Code = "ID", Name= "Indonesia"},
        new Country{ Code = "IR", Name= "Iran"},
        new Country{ Code = "IQ", Name= "Iraq"},
        new Country{ Code = "IE", Name= "Ireland"},
        new Country{ Code = "IL", Name= "Israel"},
        new Country{ Code = "IT", Name= "Italy"},
        new Country{ Code = "JM", Name= "Jamaica"},
        new Country{ Code = "JP", Name= "Japan"},
        new Country{ Code = "JO", Name= "Jordan"},
        new Country{ Code = "KZ", Name= "Kazakhstan"},
        new Country{ Code = "KE", Name= "Kenya"},
        new Country{ Code = "KI", Name= "Kiribati"},
        new Country{ Code = "KP", Name= "Korea (North"},
        new Country{ Code = "KR", Name= "Korea (South"},
        new Country{ Code = "KW", Name= "Kuwait"},
        new Country{ Code = "KG", Name= "Kyrgyzsta"},
        new Country{ Code = "LA", Name= "Laos"},
        new Country{ Code = "LV", Name= "Latvia"},
        new Country{ Code = "LB", Name= "Lebanon"},
        new Country{ Code = "LS", Name= "Lesotho"},
        new Country{ Code = "LR", Name= "Liberia"},
        new Country{ Code = "LY", Name= "Liby"},
        new Country{ Code = "LI", Name= "Liechtenstei"},
        new Country{ Code = "LT", Name= "Lithuani"},
        new Country{ Code = "LU", Name= "Luxembour"},
        new Country{ Code = "MO", Name= "Maca"},
        new Country{ Code = "MK", Name= "Macedoni"},
        new Country{ Code = "MG", Name= "Madagasca"},
        new Country{ Code = "MW", Name= "Malaw"},
        new Country{ Code = "MY", Name= "Malaysi"},
        new Country{ Code = "MV", Name= "Maldive"},
        new Country{ Code = "ML", Name= "Mal"},
        new Country{ Code = "MT", Name= "Malt"},
        new Country{ Code = "MH", Name= "Marshall Island"},
        new Country{ Code = "MQ", Name= "Martiniqu"},
        new Country{ Code = "MR", Name= "Mauritani"},
        new Country{ Code = "MU", Name= "Mauritiu"},
        new Country{ Code = "YT", Name= "Mayott"},
        new Country{ Code = "MX", Name= "Mexic"},
        new Country{ Code = "FM", Name= "Micronesi"},
        new Country{ Code = "MD", Name= "Moldov"},
        new Country{ Code = "MC", Name= "Monac"},
        new Country{ Code = "MN", Name= "Mongoli"},
        new Country{ Code = "MS", Name= "Montserra"},
        new Country{ Code = "MA", Name= "Morocc"},
        new Country{ Code = "MZ", Name= "Mozambiqu"},
        new Country{ Code = "MM", Name= "Myanma"},
        new Country{ Code = "NA", Name= "Namibi"},
        new Country{ Code = "NR", Name= "Naur"},
        new Country{ Code = "NP", Name= "Nepa"},
        new Country{ Code = "NL", Name= "Netherland"},
        new Country{ Code = "AN", Name= "Netherlands Antille"},
        new Country{ Code = "NC", Name= "New Caledoni"},
        new Country{ Code = "NZ", Name= "New Zealan"},
        new Country{ Code = "NI", Name= "Nicaragu"},
        new Country{ Code = "NE", Name= "Nige"},
        new Country{ Code = "NG", Name= "Nigeri"},
        new Country{ Code = "NU", Name= "Niu"},
        new Country{ Code = "NF", Name= "Norfolk Islan"},
        new Country{ Code = "MP", Name= "Northern Mariana Island"},
        new Country{ Code = "NO", Name= "Norwa"},
        new Country{ Code = "OM", Name= "Oma"},
        new Country{ Code = "PK", Name= "Pakista"},
        new Country{ Code = "PW", Name= "Pala"},
        new Country{ Code = "PA", Name= "Panam"},
        new Country{ Code = "PG", Name= "Papua New Guine"},
        new Country{ Code = "PY", Name= "Paragua"},
        new Country{ Code = "PE", Name= "Per"},
        new Country{ Code = "PH", Name= "Philippine"},
        new Country{ Code = "PN", Name= "Pitcair"},
        new Country{ Code = "PL", Name= "Polan"},
        new Country{ Code = "PT", Name= "Portuga"},
        new Country{ Code = "PR", Name= "Puerto Ric"},
        new Country{ Code = "QA", Name= "Qata"},
        new Country{ Code = "RE", Name= "Reunio"},
        new Country{ Code = "RO", Name= "Romani"},
        new Country{ Code = "RU", Name= "Russian Federatio"},
        new Country{ Code = "RW", Name= "Rwand"},
        new Country{ Code = "KN", Name= "Saint Kitts and Nevi"},
        new Country{ Code = "LC", Name= "Saint Luci"},
        new Country{ Code = "VC", Name= "Saint Vincent and The Grenadine"},
        new Country{ Code = "WS", Name= "Samo"},
        new Country{ Code = "SM", Name= "San Marin"},
        new Country{ Code = "ST", Name= "Sao Tome and Princip"},
        new Country{ Code = "SA", Name= "Saudi Arabi"},
        new Country{ Code = "SN", Name= "Senega"},
        new Country{ Code = "SC", Name= "Seychelle"},
        new Country{ Code = "SL", Name= "Sierra Leon"},
        new Country{ Code = "SG", Name= "Singapor"},
        new Country{ Code = "SK", Name= "Slovak Republi"},
        new Country{ Code = "SI", Name= "Sloveni"},
        new Country{ Code = "SB", Name= "Solomon Island"},
        new Country{ Code = "SO", Name= "Somali"},
        new Country{ Code = "ZA", Name= "South Afric"},
        new Country{ Code = "GS", Name= "S. Georgia and S. Sandwich Isls"},
        new Country{ Code = "ES", Name= "Spai"},
        new Country{ Code = "LK", Name= "Sri Lank"},
        new Country{ Code = "SH", Name= "St. Helen"},
        new Country{ Code = "PM", Name= "St. Pierre and Miquelo"},
        new Country{ Code = "SD", Name= "Suda"},
        new Country{ Code = "SR", Name= "Surinam"},
        new Country{ Code = "SJ", Name= "Svalbard and Jan Mayen Island"},
        new Country{ Code = "SZ", Name= "Swazilan"},
        new Country{ Code = "SE", Name= "Swede"},
        new Country{ Code = "CH", Name= "Switzerlan"},
        new Country{ Code = "SY", Name= "Syri"},
        new Country{ Code = "TW", Name= "Taiwa"},
        new Country{ Code = "TJ", Name= "Tajikista"},
        new Country{ Code = "TZ", Name= "Tanzani"},
        new Country{ Code = "TH", Name= "Thailan"},
        new Country{ Code = "TG", Name= "Tog"},
        new Country{ Code = "TK", Name= "Tokela"},
        new Country{ Code = "TO", Name= "Tong"},
        new Country{ Code = "TT", Name= "Trinidad and Tobag"},
        new Country{ Code = "TN", Name= "Tunisi"},
        new Country{ Code = "TR", Name= "Turke"},
        new Country{ Code = "TM", Name= "Turkmenista"},
        new Country{ Code = "TC", Name= "Turks and Caicos Island"},
        new Country{ Code = "TV", Name= "Tuval"},
        new Country{ Code = "UG", Name= "Ugand"},
        new Country{ Code = "UA", Name= "Ukrain"},
        new Country{ Code = "AE", Name= "United Arab Emirate"},
        new Country{ Code = "UK", Name= "United Kingdo"},
        new Country{ Code = "US", Name= "United State"},
        new Country{ Code = "UM", Name= "US Minor Outlying Island"},
        new Country{ Code = "UY", Name= "Urugua"},
        new Country{ Code = "UZ", Name= "Uzbekista"},
        new Country{ Code = "VU", Name= "Vanuat"},
        new Country{ Code = "VA", Name= "Vatican City State (Holy See"},
        new Country{ Code = "VE", Name= "Venezuel"},
        new Country{ Code = "VN", Name= "Viet Na"},
        new Country{ Code = "VG", Name= "Virgin Islands (British"},
        new Country{ Code = "VI", Name= "Virgin Islands (US"},
        new Country{ Code = "WF", Name= "Wallis and Futuna Island"},
        new Country{ Code = "EH", Name= "Western Sahar"},
        new Country{ Code = "YE", Name= "Yeme"},
        new Country{ Code = "YU", Name= "Yugoslavi"},
        new Country{ Code = "ZR", Name= "Zair"},
        new Country{ Code = "ZM", Name= "Zambi"},
        new Country{ Code = "ZW", Name= "Zimbabw"}
        };
    }
}
